# Generated by Django 5.0.1 on 2024-01-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation_chromosome', models.CharField(max_length=255, verbose_name='Тип мутации')),
                ('number_chromosome', models.IntegerField(verbose_name='Номер хромосомы')),
                ('individ_age', models.IntegerField(verbose_name='Номер хромосомы')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
        ),
    ]
