# Generated by Django 5.0.1 on 2024-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_individ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individ',
            name='individ_age',
            field=models.IntegerField(verbose_name='Возраст индивида'),
        ),
    ]
