# Generated by Django 5.0.1 on 2024-02-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_individ_individ_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='individ',
            name='count_blood',
            field=models.IntegerField(default=0, verbose_name='Кровь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individ',
            name='count_chorion',
            field=models.IntegerField(default=0, verbose_name='Хорион'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individ',
            name='count_dna',
            field=models.IntegerField(default=0, verbose_name='ДНК'),
            preserve_default=False,
        ),
    ]
